configName: pic32mm_usb_curiosity
folderName: pic32mm_usb_curiosity
format_version: v1.0
frameworkPath: ..\..\..
processor: PIC32MM0256GPM064
projectName: cdc_com_port_dual_pic32mm_usb_curiosity
settings:
  PackageFilter: bsp;core;csp;quick_docs;usb;usb_apps_device;usb_apps_dual_role;usb_apps_host;usb_apps_multi_controller
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MM_GPM_DFP\1.3.50\atdf\PIC32MM0256GPM064.atdf
