configName: sam_a5d2_xult
folderName: sam_a5d2_xult
format_version: v1.0
frameworkPath: ..\..\..
processor: ATSAMA5D27
projectName: cdc_msd_sdcard_sam_a5d2_xult
settings:
  PackageFilter: audio;bootloader;bootloader_apps_usb;bsp;core;core_apps_pic32mx;core_apps_pic32mz_w1;csp;csp_apps_pic32cz_ca;csp_apps_sam_d21_da1;quick_docs;reference_apps;usb;usb_apps_device;usb_apps_dual_role;usb_apps_host;usb_apps_multi_controller
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMA5D2_DFP\1.6.69\atdf\ATSAMA5D27.atdf
