configName: sam_9x60_ek_iar
folderName: sam_9x60_ek_iar.IAR
format_version: v1.0
frameworkPath: C:\Repos\H3
processor: SAM9X60
projectName: msd_sdcard_sam_9x60_ek_iar
settings:
  PackageFilter: audio;bsp;core;core_apps_sam_9x60;core_apps_sam_a5d2;csp;csp_apps_pic32cm_le_ls;csp_apps_sam_9x60;csp_apps_sam_a5d2;usb;usb_apps_device;usb_apps_dual_role;usb_apps_host;usb_apps_multi_controller;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAM9X60_DFP\1.4.40\atdf\SAM9X60.atdf
