configName: sam_a5d2_xult_iar
folderName: ''
format_version: v1.0
frameworkPath: C:\Repos\H3
processor: ATSAMA5D27
projectName: cdc_com_port_single_sam_a5d2_xult_iar
settings:
  PackageFilter: bsp;core;core_apps_sam_a7g5;csp;Devices;dev_packs;quick_docs;usb;usb_apps_device;usb_apps_dual_role;usb_apps_host;usb_apps_multi_controller
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMA5D2_DFP\1.6.69\atdf\ATSAMA5D27.atdf
