package:
  format-version: "1.0.0"
  name: "usb_apps_device"
  version: "v3.7.0"
  type: "application"
  status: "production"
  required: false

  dependencies:
    - name: "usb"
      type: "package"
      version: "v3.13.0"
    - name: "csp"
      type: "package"
      version: "v3.18.5"
    - name: "core"
      type: "package"
      version: "v3.13.4"
    - name: "bsp"
      type: "package"
      version: "v3.19.0"


