package:
  format-version: "1.0.0"
  name: "usb_apps_device"
  version: "v3.8.0"
  type: "application"
  status: "production"
  required: false

  dependencies:
    - name: "usb"
      type: "package"
      version: "v3.14.0"
    - name: "bsp"
      type: "package"
      version: "v3.20.1"


