package:
  format-version: "1.0.0"
  name: "usb_apps_device"
  version: "3.5.0-E1"
  type: "application"
  status: "production"
  required: true

  dependencies:
    - name: "usb"
      type: "package"
      version: "3.11.0-E1"
    - name: "csp"
      type: "package"
      version: "3.15.0-E1"
    - name: "core"
      type: "package"
      version: "3.11.1"
    - name: "bsp"
      type: "package"
      version: "3.15.0-E1"


