configName: sam_e54_xpro
folderName: sam_e54_xpro
format_version: v1.0
frameworkPath: ..\..\..
processor: ATSAME54P20A
projectName: usb_uart_bridge_single_sam_e54_xpro
settings:
  PackageFilter: bsp;core;core_apps_pic32mx;core_apps_sam_9x60;core_apps_sam_d21_da1;core_apps_sam_d5x_e5x;core_apps_sam_e70_s70_v70_v71;core_apps_sam_g55;crypto;csp;csp_apps_pic32mx;csp_apps_sam_9x60;csp_apps_sam_d21_da1;csp_apps_sam_d5x_e5x;csp_apps_sam_e70_s70_v70_v71;csp_apps_sam_g55;net;quick_docs;usb;usb-dft;usb_apps_device;usb_apps_dual_role;usb_apps_host;usb_apps_multi_controller;validation
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: ALL
  DFPPath: .\dev_packs\Microchip\SAME54_DFP\3.5.87\atdf\ATSAME54P20A.atdf
