configName: sam_e54_xpro
folderName: sam_e54_xpro
format_version: v1.0
frameworkPath: ..\..\..
processor: ATSAME54P20A
projectName: usb_uart_bridge_single_sam_e54_xpro
settings:
  PackageFilter: audio;bsp;core;csp;quick_docs;usb;usb_apps_device;usb_apps_dual_role;usb_apps_host;usb_apps_multi_controller
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAME54_DFP\3.5.87\atdf\ATSAME54P20A.atdf
