format_version: v1.0
configName: sam_9x60_curiosity_freertos
folderName: sam_9x60_curiosity_freertos
frameworkPath: C:\h3_gh
processor: SAM9X60D1G
projectName: sam_9x60_curiosity_freertos
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\SAM9X60_DFP\1.7.85\atdf\SAM9X60D1G.atdf
