format_version: v1.0
type: UniqueComponent
attributes: {id: BSP_SAM_A7G5_Evaluation_Kit, bsp: 'true'}
children:
- type: ElementPosition
  attributes: {x: '176', y: '80', id: BSP_SAM_A7G5_Evaluation_Kit}
