configName: sam_da1_xpro
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: ATSAMDA1J16B
projectName: ''
settings:
  PackageFilter: bsp;core;csp;csp_apps_pic32mk;quick_docs;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: SAMDA1_DFP\2.7.82
