configName: pic32mx470_curiosity
folderName: pic32mx470_curiosity
format_version: v1.0
frameworkPath: ..\..\..
processor: PIC32MX470F512H
projectName: cdc_msd_sdcard_pic32mx470_curiosity
settings:
  PackageFilter: bsp;core;core_apps_pic32mx;core_apps_pic32mz_ef;csp;usb;usb_apps_device;usb_apps_dual_role;usb_apps_host;usb_apps_multi_controller
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MX_DFP\1.5.259\atdf\PIC32MX470F512H.atdf
