configName: sam_e54_xpro
folderName: sam_e54_xpro
format_version: v1.0
frameworkPath: D:\USBR3.90_testing
processor: ATSAME54P20A
projectName: sam_e54_xpro
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: SAME54_DFP\3.8.234
