configName: sam_9x60_ek_freertos
folderName: sam_9x60_ek_freertos
format_version: v1.0
frameworkPath: ..\..\..\..
processor: SAM9X60
projectName: cdc_com_port_single_sam_9x60_ek_freertos
settings:
  PackageFilter: audio;bsp;core;core_apps_sam_9x60;core_apps_sam_a5d2;csp;csp_apps_pic32cm_le_ls;csp_apps_sam_9x60;usb;usb_apps_device;usb_apps_dual_role;usb_apps_host;usb_apps_multi_controller;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAM9X60_DFP\1.4.40\atdf\SAM9X60.atdf
