/*******************************************************************************
  System Initialization File

  File Name:
    initialization.c

  Summary:
    This file contains source code necessary to initialize the system.

  Description:
    This file contains source code necessary to initialize the system.  It
    implements the "SYS_Initialize" function, defines the configuration bits,
    and allocates any necessary global system resources,
 *******************************************************************************/

// DOM-IGNORE-BEGIN
/*******************************************************************************
* Copyright (C) 2018 Microchip Technology Inc. and its subsidiaries.
*
* Subject to your compliance with these terms, you may use Microchip software
* and any derivatives exclusively with Microchip products. It is your
* responsibility to comply with third party license terms applicable to your
* use of third party software (including open source software) that may
* accompany Microchip software.
*
* THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
* EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
* WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
* PARTICULAR PURPOSE.
*
* IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
* INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
* WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
* BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
* FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
* ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
* THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *******************************************************************************/
// DOM-IGNORE-END

// *****************************************************************************
// *****************************************************************************
// Section: Included Files
// *****************************************************************************
// *****************************************************************************
#include "configuration.h"
#include "definitions.h"
#include "device.h"


// ****************************************************************************
// ****************************************************************************
// Section: Configuration Bits
// ****************************************************************************
// ****************************************************************************
#pragma config FUSES_BOOTCFG1_DEVSIGN_SEQ = 0x1U
#pragma config FUSES_BOOTCFG1_DEVSIGN_SEQBAR = 0xfffeU
#pragma config FUSES_BOOTCFG1_BOOT_FLAG_PUFRETRY = CLEAR
#pragma config FUSES_BOOTCFG1_BOOT_FLAG_PUFSTARTUP = CLEAR
#pragma config FUSES_BOOTCFG1_BOOT_FLAG_DICEDIS = SET
#pragma config FUSES_BOOTCFG1_BOOT_FLAG_BOOTMODE = SET
#pragma config FUSES_BOOTCFG1_BOOT_FLAG_RAM_INIT_ENB = SET
#pragma config FUSES_BOOTCFG1_BOOT_FLAG_PUFSCORE = 0x0U
#pragma config FUSES_BOOTCFG1_DICE_CDI_INDEX_DICE_CDI_INDEX = 0x7fU
#pragma config FUSES_BOOTCFG1_DICE_FW_HASH_INDEX_DICE_FW_HASH_INDEX = 0x7fU
#pragma config FUSES_BOOTCFG1_BOOT_GPIOSEL_GPIOPINSEL = 0x1fU
#pragma config FUSES_BOOTCFG1_BOOT_GPIOSEL_GPIOPORTSEL = 0xfU
#pragma config FUSES_BOOTCFG1_BOOT_GPIOSEL_FLTPOL = SET
#pragma config FUSES_BOOTCFG1_BOOT_GPIOSEL_FLTODRAIN = SET
#pragma config FUSES_BOOTCFG1_BOOT_GPIOSEL_FLTSLEWLIM = 0x3U
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC0 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC1 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC2 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC3 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC4 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC5 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC6 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC7 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC8 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC9 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC10 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC11 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC12 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC13 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC14 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC15 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC16 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC17 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC18 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC19 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC20 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC21 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC22 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC23 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC24 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC25 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC26 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC27 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC28 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC29 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC30 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC31 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC0 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC1 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC2 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC3 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC4 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC5 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC6 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC7 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC8 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC9 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC10 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC11 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC12 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC13 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC14 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC15 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC16 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC17 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC18 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC19 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC20 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC21 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC22 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC23 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC24 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC25 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC26 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC27 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC28 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC29 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC30 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC31 = CLEAR
#pragma config FUSES_BOOTCFG1_PAC_WRCTRL_H2PB0_PERID = 0x13U
#pragma config FUSES_BOOTCFG1_PAC_WRCTRL_H2PB0_KEY = OFF
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC0 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC1 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC2 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC3 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC4 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC5 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC6 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC7 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC8 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC9 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC10 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC11 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC12 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC13 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC14 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC15 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC16 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC17 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC18 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC19 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC20 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC21 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC22 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC23 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC24 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC25 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC26 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC27 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC28 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC29 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC30 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC31 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC0 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC1 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC2 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC3 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC4 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC5 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC6 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC7 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC8 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC9 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC10 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC11 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC12 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC13 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC14 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC15 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC16 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC17 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC18 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC19 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC20 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC21 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC22 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC23 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC24 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC25 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC26 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC27 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC28 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC29 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC30 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC31 = CLEAR
#pragma config FUSES_BOOTCFG1_PAC_WRCTRL_H2PB1_PERID = 0x2eU
#pragma config FUSES_BOOTCFG1_PAC_WRCTRL_H2PB1_KEY = OFF
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC0 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC1 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC2 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC3 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC4 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC5 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC6 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC7 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC8 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC9 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC10 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC11 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC12 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC13 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC14 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC15 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC16 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC17 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC18 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC19 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC20 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC21 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC22 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC23 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC24 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC25 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC26 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC27 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC28 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC29 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC30 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC31 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC0 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC1 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC2 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC3 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC4 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC5 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC6 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC7 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC8 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC9 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC10 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC11 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC12 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC13 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC14 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC15 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC16 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC17 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC18 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC19 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC20 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC21 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC22 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC23 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC24 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC25 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC26 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC27 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC28 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC29 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC30 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC31 = CLEAR
#pragma config FUSES_BOOTCFG1_PAC_WRCTRL_H2PB2_PERID = 0x2fU
#pragma config FUSES_BOOTCFG1_PAC_WRCTRL_H2PB2_KEY = OFF
#pragma config FUSES_BOOTCFG1_IDAU_RCTRL_BFM_ARG = 0x0U
#pragma config FUSES_BOOTCFG1_IDAU_RCTRL_BFM_CMD = WRSZ
#pragma config FUSES_BOOTCFG1_IDAU_RCTRL_PFMANS_ARG = 0x0U
#pragma config FUSES_BOOTCFG1_IDAU_RCTRL_PFMANS_CMD = WRSZ
#pragma config FUSES_BOOTCFG1_IDAU_RCTRL_PFMANSC_ARG = 0x0U
#pragma config FUSES_BOOTCFG1_IDAU_RCTRL_PFMANSC_CMD = WRSZ
#pragma config FUSES_BOOTCFG1_IDAU_RCTRL_DRM_ARG = 0x0U
#pragma config FUSES_BOOTCFG1_IDAU_RCTRL_DRM_CMD = WRSZ
#pragma config FUSES_BOOTCFG1_IDAU_CTRL_EN_CMD = ENABLE
#pragma config FUSES_BOOTCFG1_IDAU_CTRL_WLCK_CMD = WLCK
#pragma config FUSES_BOOTCFG1_FCW_CWP_BC1AWP = DISABLE
#pragma config FUSES_BOOTCFG1_FCW_CWP_BC1WP = DISABLE
#pragma config FUSES_BOOTCFG1_FCW_CWP_RCWP = DISABLE
#pragma config FUSES_BOOTCFG1_FCW_CWP_VSSWP0 = DISABLE
#pragma config FUSES_BOOTCFG1_FCW_CWP_VSSWP1 = DISABLE
#pragma config FUSES_BOOTCFG1_FCW_CWP_BC1AWPLOCK = UNLOCKED
#pragma config FUSES_BOOTCFG1_FCW_CWP_BC1WPLOCK = UNLOCKED
#pragma config FUSES_BOOTCFG1_FCW_CWP_RCWPLOCK = UNLOCKED
#pragma config FUSES_BOOTCFG1_FCW_CWP_VSSWPLOCK0 = UNLOCKED
#pragma config FUSES_BOOTCFG1_FCW_CWP_VSSWPLOCK1 = UNLOCKED
#pragma config FUSES_BOOTCFG1_FCR_CRP_BC1ARP = DISABLE
#pragma config FUSES_BOOTCFG1_FCR_CRP_BC1RP = DISABLE
#pragma config FUSES_BOOTCFG1_FCR_CRP_RCRP = DISABLE
#pragma config FUSES_BOOTCFG1_FCR_CRP_VSSRP0 = DISABLE
#pragma config FUSES_BOOTCFG1_FCR_CRP_VSSRP1 = DISABLE
#pragma config FUSES_BOOTCFG1_FCR_CRP_BC1ARPLOCK = UNLOCKED
#pragma config FUSES_BOOTCFG1_FCR_CRP_BC1RPLOCK = UNLOCKED
#pragma config FUSES_BOOTCFG1_FCR_CRP_RCRPLOCK = UNLOCKED
#pragma config FUSES_BOOTCFG1_FCR_CRP_VSSRPLOCK0 = UNLOCKED
#pragma config FUSES_BOOTCFG1_FCR_CRP_VSSRPLOCK1 = UNLOCKED
#pragma config FUSES_BOOTCFG1_FCR_ECCCTRL_ECCCTL = STRICT
#pragma config FUSES_BOOTCFG1_FCR_ECCCTRL_ECCUNLCK = LOCKED
#pragma config FUSES_BOOTCFG1_FCR_ECCCTRL_SECCNT = 0x0U
#pragma config FUSES_BOOTCFG1_SUPC_BRCFGUSMOR_BOR_HYST_BOR_VDDIO = LOW
#pragma config FUSES_BOOTCFG1_SUPC_BRCFGUSMOR_BOR_BOR_TRIP_VDDIO = 0x0U
#pragma config FUSES_BOOTCFG1_SUPC_BRCFGUSMOR_BOR_HYST_BOR_VDDREG = LOW
#pragma config FUSES_BOOTCFG1_SUPC_BRCFGUDSSMOR_BOR_HYST = LOW
#pragma config FUSES_BOOTCFG1_SUPC_BRCFGUDSSMOR_BOR_TRIP = 0x0U
#pragma config FUSES_BOOTCFG1_SUPC_BRCFGUCP0_CP = 0x0U
#pragma config FUSES_BOOTCFG1_WDT_SETUP_ENABLE = CLEAR
#pragma config FUSES_BOOTCFG1_WDT_SETUP_WEN = CLEAR
#pragma config FUSES_BOOTCFG1_WDT_SETUP_RUNSTDBY = CLEAR
#pragma config FUSES_BOOTCFG1_WDT_SETUP_ALWAYSON = CLEAR
#pragma config FUSES_BOOTCFG1_WDT_SETUP_PER = CYC8
#pragma config FUSES_BOOTCFG1_WDT_SETUP_WINDOW = CYC8
#pragma config FUSES_BOOTCFG1_WDT_SETUP_EWOFFSET = CYC8
#pragma config FUSES_BOOTCFG1A_DEVSIGN_SEQ = 0x2U
#pragma config FUSES_BOOTCFG1A_DEVSIGN_SEQBAR = 0xfffdU
#pragma config FUSES_BOOTCFG1A_BOOT_FLAG_PUFRETRY = CLEAR
#pragma config FUSES_BOOTCFG1A_BOOT_FLAG_PUFSTARTUP = CLEAR
#pragma config FUSES_BOOTCFG1A_BOOT_FLAG_DICEDIS = SET
#pragma config FUSES_BOOTCFG1A_BOOT_FLAG_BOOTMODE = SET
#pragma config FUSES_BOOTCFG1A_BOOT_FLAG_RAM_INIT_ENB = SET
#pragma config FUSES_BOOTCFG1A_BOOT_FLAG_PUFSCORE = 0x0U
#pragma config FUSES_BOOTCFG1A_DICE_CDI_INDEX_DICE_CDI_INDEX = 0x7fU
#pragma config FUSES_BOOTCFG1A_DICE_FW_HASH_INDEX_DICE_FW_HASH_INDEX = 0x7fU
#pragma config FUSES_BOOTCFG1A_BOOT_GPIOSEL_GPIOPINSEL = 0x1fU
#pragma config FUSES_BOOTCFG1A_BOOT_GPIOSEL_GPIOPORTSEL = 0xfU
#pragma config FUSES_BOOTCFG1A_BOOT_GPIOSEL_FLTPOL = SET
#pragma config FUSES_BOOTCFG1A_BOOT_GPIOSEL_FLTODRAIN = SET
#pragma config FUSES_BOOTCFG1A_BOOT_GPIOSEL_FLTSLEWLIM = 0x3U
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC0 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC1 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC2 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC3 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC4 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC5 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC6 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC7 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC8 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC9 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC10 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC11 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC12 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC13 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC14 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC15 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC16 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC17 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC18 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC19 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC20 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC21 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC22 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC23 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC24 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC25 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC26 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC27 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC28 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC29 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC30 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC31 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC0 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC1 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC2 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC3 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC4 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC5 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC6 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC7 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC8 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC9 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC10 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC11 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC12 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC13 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC14 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC15 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC16 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC17 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC18 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC19 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC20 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC21 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC22 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC23 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC24 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC25 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC26 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC27 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC28 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC29 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC30 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC31 = CLEAR
#pragma config FUSES_BOOTCFG1A_PAC_WRCTRL_H2PB0_PERID = 0x13U
#pragma config FUSES_BOOTCFG1A_PAC_WRCTRL_H2PB0_KEY = OFF
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC0 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC1 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC2 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC3 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC4 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC5 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC6 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC7 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC8 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC9 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC10 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC11 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC12 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC13 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC14 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC15 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC16 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC17 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC18 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC19 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC20 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC21 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC22 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC23 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC24 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC25 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC26 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC27 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC28 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC29 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC30 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC31 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC0 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC1 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC2 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC3 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC4 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC5 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC6 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC7 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC8 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC9 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC10 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC11 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC12 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC13 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC14 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC15 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC16 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC17 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC18 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC19 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC20 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC21 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC22 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC23 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC24 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC25 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC26 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC27 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC28 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC29 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC30 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC31 = CLEAR
#pragma config FUSES_BOOTCFG1A_PAC_WRCTRL_H2PB1_PERID = 0x2eU
#pragma config FUSES_BOOTCFG1A_PAC_WRCTRL_H2PB1_KEY = OFF
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC0 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC1 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC2 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC3 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC4 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC5 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC6 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC7 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC8 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC9 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC10 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC11 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC12 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC13 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC14 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC15 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC16 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC17 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC18 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC19 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC20 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC21 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC22 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC23 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC24 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC25 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC26 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC27 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC28 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC29 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC30 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC31 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC0 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC1 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC2 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC3 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC4 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC5 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC6 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC7 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC8 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC9 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC10 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC11 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC12 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC13 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC14 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC15 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC16 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC17 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC18 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC19 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC20 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC21 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC22 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC23 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC24 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC25 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC26 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC27 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC28 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC29 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC30 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC31 = CLEAR
#pragma config FUSES_BOOTCFG1A_PAC_WRCTRL_H2PB2_PERID = 0x2fU
#pragma config FUSES_BOOTCFG1A_PAC_WRCTRL_H2PB2_KEY = OFF
#pragma config FUSES_BOOTCFG1A_IDAU_RCTRL_BFM_ARG = 0x0U
#pragma config FUSES_BOOTCFG1A_IDAU_RCTRL_BFM_CMD = WRSZ
#pragma config FUSES_BOOTCFG1A_IDAU_RCTRL_PFMANS_ARG = 0x0U
#pragma config FUSES_BOOTCFG1A_IDAU_RCTRL_PFMANS_CMD = WRSZ
#pragma config FUSES_BOOTCFG1A_IDAU_RCTRL_PFMANSC_ARG = 0x0U
#pragma config FUSES_BOOTCFG1A_IDAU_RCTRL_PFMANSC_CMD = WRSZ
#pragma config FUSES_BOOTCFG1A_IDAU_RCTRL_DRM_ARG = 0x0U
#pragma config FUSES_BOOTCFG1A_IDAU_RCTRL_DRM_CMD = WRSZ
#pragma config FUSES_BOOTCFG1A_IDAU_CTRL_EN_CMD = ENABLE
#pragma config FUSES_BOOTCFG1A_IDAU_CTRL_WLCK_CMD = WLCK
#pragma config FUSES_BOOTCFG1A_FCW_CWP_BC1AWP = DISABLE
#pragma config FUSES_BOOTCFG1A_FCW_CWP_BC1WP = DISABLE
#pragma config FUSES_BOOTCFG1A_FCW_CWP_RCWP = DISABLE
#pragma config FUSES_BOOTCFG1A_FCW_CWP_VSSWP0 = DISABLE
#pragma config FUSES_BOOTCFG1A_FCW_CWP_VSSWP1 = DISABLE
#pragma config FUSES_BOOTCFG1A_FCW_CWP_BC1AWPLOCK = UNLOCKED
#pragma config FUSES_BOOTCFG1A_FCW_CWP_BC1WPLOCK = UNLOCKED
#pragma config FUSES_BOOTCFG1A_FCW_CWP_RCWPLOCK = UNLOCKED
#pragma config FUSES_BOOTCFG1A_FCW_CWP_VSSWPLOCK0 = UNLOCKED
#pragma config FUSES_BOOTCFG1A_FCW_CWP_VSSWPLOCK1 = UNLOCKED
#pragma config FUSES_BOOTCFG1A_FCR_CRP_BC1ARP = DISABLE
#pragma config FUSES_BOOTCFG1A_FCR_CRP_BC1RP = DISABLE
#pragma config FUSES_BOOTCFG1A_FCR_CRP_RCRP = DISABLE
#pragma config FUSES_BOOTCFG1A_FCR_CRP_VSSRP0 = DISABLE
#pragma config FUSES_BOOTCFG1A_FCR_CRP_VSSRP1 = DISABLE
#pragma config FUSES_BOOTCFG1A_FCR_CRP_BC1ARPLOCK = UNLOCKED
#pragma config FUSES_BOOTCFG1A_FCR_CRP_BC1RPLOCK = UNLOCKED
#pragma config FUSES_BOOTCFG1A_FCR_CRP_RCRPLOCK = UNLOCKED
#pragma config FUSES_BOOTCFG1A_FCR_CRP_VSSRPLOCK0 = UNLOCKED
#pragma config FUSES_BOOTCFG1A_FCR_CRP_VSSRPLOCK1 = UNLOCKED
#pragma config FUSES_BOOTCFG1A_FCR_ECCCTRL_ECCCTL = STRICT
#pragma config FUSES_BOOTCFG1A_FCR_ECCCTRL_ECCUNLCK = LOCKED
#pragma config FUSES_BOOTCFG1A_FCR_ECCCTRL_SECCNT = 0x0U
#pragma config FUSES_BOOTCFG1A_SUPC_BRCFGUSMOR_BOR_HYST_BOR_VDDIO = LOW
#pragma config FUSES_BOOTCFG1A_SUPC_BRCFGUSMOR_BOR_BOR_TRIP_VDDIO = 0x0U
#pragma config FUSES_BOOTCFG1A_SUPC_BRCFGUSMOR_BOR_HYST_BOR_VDDREG = LOW
#pragma config FUSES_BOOTCFG1A_SUPC_BRCFGUDSSMOR_BOR_HYST = LOW
#pragma config FUSES_BOOTCFG1A_SUPC_BRCFGUDSSMOR_BOR_TRIP = 0x0U
#pragma config FUSES_BOOTCFG1A_SUPC_BRCFGUCP0_CP = 0x0U
#pragma config FUSES_BOOTCFG1A_WDT_SETUP_ENABLE = CLEAR
#pragma config FUSES_BOOTCFG1A_WDT_SETUP_WEN = CLEAR
#pragma config FUSES_BOOTCFG1A_WDT_SETUP_RUNSTDBY = CLEAR
#pragma config FUSES_BOOTCFG1A_WDT_SETUP_ALWAYSON = CLEAR
#pragma config FUSES_BOOTCFG1A_WDT_SETUP_PER = CYC8
#pragma config FUSES_BOOTCFG1A_WDT_SETUP_WINDOW = CYC8
#pragma config FUSES_BOOTCFG1A_WDT_SETUP_EWOFFSET = CYC8




// *****************************************************************************
// *****************************************************************************
// Section: Driver Initialization Data
// *****************************************************************************
// *****************************************************************************
/* Following MISRA-C rules are deviated in the below code block */
/* MISRA C-2012 Rule 7.2 - Deviation record ID - H3_MISRAC_2012_R_7_2_DR_1 */
/* MISRA C-2012 Rule 11.1 - Deviation record ID - H3_MISRAC_2012_R_11_1_DR_1 */
/* MISRA C-2012 Rule 11.3 - Deviation record ID - H3_MISRAC_2012_R_11_3_DR_1 */
/* MISRA C-2012 Rule 11.8 - Deviation record ID - H3_MISRAC_2012_R_11_8_DR_1 */
// <editor-fold defaultstate="collapsed" desc="DRV_USART Instance 0 Initialization Data">

static DRV_USART_CLIENT_OBJ drvUSART0ClientObjPool[DRV_USART_CLIENTS_NUMBER_IDX0];

/* USART transmit/receive transfer objects pool */
static DRV_USART_BUFFER_OBJ drvUSART0BufferObjPool[DRV_USART_QUEUE_SIZE_IDX0];

static const DRV_USART_PLIB_INTERFACE drvUsart0PlibAPI = {
    .readCallbackRegister = (DRV_USART_PLIB_READ_CALLBACK_REG)SERCOM4_USART_ReadCallbackRegister,
    .read_t = (DRV_USART_PLIB_READ)SERCOM4_USART_Read,
    .readIsBusy = (DRV_USART_PLIB_READ_IS_BUSY)SERCOM4_USART_ReadIsBusy,
    .readCountGet = (DRV_USART_PLIB_READ_COUNT_GET)SERCOM4_USART_ReadCountGet,
    .readAbort = (DRV_USART_PLIB_READ_ABORT)SERCOM4_USART_ReadAbort,
    .writeCallbackRegister = (DRV_USART_PLIB_WRITE_CALLBACK_REG)SERCOM4_USART_WriteCallbackRegister,
    .write_t = (DRV_USART_PLIB_WRITE)SERCOM4_USART_Write,
    .writeIsBusy = (DRV_USART_PLIB_WRITE_IS_BUSY)SERCOM4_USART_WriteIsBusy,
    .writeCountGet = (DRV_USART_PLIB_WRITE_COUNT_GET)SERCOM4_USART_WriteCountGet,
    .errorGet = (DRV_USART_PLIB_ERROR_GET)SERCOM4_USART_ErrorGet,
    .serialSetup = (DRV_USART_PLIB_SERIAL_SETUP)SERCOM4_USART_SerialSetup
};

static const uint32_t drvUsart0remapDataWidth[] = { 0x5, 0x6, 0x7, 0x0, 0x1 };
static const uint32_t drvUsart0remapParity[] = { 0x2, 0x0, 0x80000, 0xFFFFFFFFU, 0xFFFFFFFFU, 0xFFFFFFFFU };
static const uint32_t drvUsart0remapStopBits[] = { 0x0, 0xFFFFFFFFU, 0x40 };
static const uint32_t drvUsart0remapError[] = { 0x4, 0x0, 0x2 };

static const DRV_USART_INTERRUPT_SOURCES drvUSART0InterruptSources =
{
    /* Peripheral has more than one interrupt vector */
    .isSingleIntSrc                        = false,

    /* Peripheral interrupt lines */
   .intSources.multi.usartTxCompleteInt   = (int32_t)SERCOM4_1_IRQn,
   .intSources.multi.usartTxReadyInt      = (int32_t)SERCOM4_0_IRQn,
   .intSources.multi.usartRxCompleteInt   = (int32_t)SERCOM4_2_IRQn,
   .intSources.multi.usartErrorInt        = (int32_t)SERCOM4_6_IRQn,        
};

static const DRV_USART_INIT drvUsart0InitData =
{
    .usartPlib = &drvUsart0PlibAPI,

    /* USART Number of clients */
    .numClients = DRV_USART_CLIENTS_NUMBER_IDX0,

    /* USART Client Objects Pool */
    .clientObjPool = (uintptr_t)&drvUSART0ClientObjPool[0],

    /* Combined size of transmit and receive buffer objects */
    .bufferObjPoolSize = DRV_USART_QUEUE_SIZE_IDX0,

    /* USART transmit and receive buffer buffer objects pool */
    .bufferObjPool = (uintptr_t)&drvUSART0BufferObjPool[0],

    .interruptSources = &drvUSART0InterruptSources,

    .remapDataWidth = drvUsart0remapDataWidth,

    .remapParity = drvUsart0remapParity,

    .remapStopBits = drvUsart0remapStopBits,

    .remapError = drvUsart0remapError,

    .dataWidth = DRV_USART_DATA_8_BIT,
};

// </editor-fold>
// <editor-fold defaultstate="collapsed" desc="DRV_MEMORY Instance 0 Initialization Data">

static uint8_t gDrvMemory0EraseBuffer[FCW_ERASE_BUFFER_SIZE] CACHE_ALIGN;

static DRV_MEMORY_CLIENT_OBJECT gDrvMemory0ClientObject[DRV_MEMORY_CLIENTS_NUMBER_IDX0];

static DRV_MEMORY_BUFFER_OBJECT gDrvMemory0BufferObject[DRV_MEMORY_BUF_Q_SIZE_IDX0];

static const DRV_MEMORY_DEVICE_INTERFACE drvMemory0DeviceAPI = {
    .Open               = DRV_FCW_Open,
    .Close              = DRV_FCW_Close,
    .Status             = DRV_FCW_Status,
    .SectorErase        = DRV_FCW_SectorErase,
    .Read               = DRV_FCW_Read,
    .PageWrite          = DRV_FCW_PageWrite,
    .EventHandlerSet    = NULL,
    .GeometryGet        = (DRV_MEMORY_DEVICE_GEOMETRY_GET)DRV_FCW_GeometryGet,
    .TransferStatusGet  = (DRV_MEMORY_DEVICE_TRANSFER_STATUS_GET)DRV_FCW_TransferStatusGet
};
static const DRV_MEMORY_INIT drvMemory0InitData =
{
    .memDevIndex                = 0,
    .memoryDevice               = &drvMemory0DeviceAPI,
    .isMemDevInterruptEnabled   = false,
    .isFsEnabled                = false,
    .ewBuffer                   = &gDrvMemory0EraseBuffer[0],
    .clientObjPool              = (uintptr_t)&gDrvMemory0ClientObject[0],
    .bufferObj                  = (uintptr_t)&gDrvMemory0BufferObject[0],
    .queueSize                  = DRV_MEMORY_BUF_Q_SIZE_IDX0,
    .nClientsMax                = DRV_MEMORY_CLIENTS_NUMBER_IDX0
};

// </editor-fold>



// *****************************************************************************
// *****************************************************************************
// Section: System Data
// *****************************************************************************
// *****************************************************************************
/* Structure to hold the object handles for the modules in the system. */
SYSTEM_OBJECTS sysObj;

// *****************************************************************************
// *****************************************************************************
// Section: Library/Stack Initialization Data
// *****************************************************************************
// *****************************************************************************
/******************************************************
 * USB Driver Initialization
 ******************************************************/
 
/*  When designing a Self-powered USB Device, the application should make sure
    that USB_DEVICE_Attach() function is called only when VBUS is actively powered.
    Therefore, the firmware needs some means to detect when the Host is powering 
    the VBUS. A 5V tolerant I/O pin can be connected to VBUS (through a resistor)
    and can be used to detect when VBUS is high or low. The application can specify
    a VBUS Detect function through the USB Driver Initialize data structure. 
    The USB device stack will periodically call this function. If the VBUS is 
    detected, the USB_DEVICE_EVENT_POWER_DETECTED event is generated. If the VBUS 
    is removed (i.e., the device is physically detached from Host), the USB stack 
    will generate the event USB_DEVICE_EVENT_POWER_REMOVED. The application should 
    call USB_DEVICE_Detach() when VBUS is removed. 
    
    The following are the steps to generate the VBUS_SENSE Function through MHC     
        1) Navigate to MHC->Tools->Pin Configuration and Configure the pin used 
           as VBUS_SENSE. Set this pin Function as "GPIO" and set as "Input". 
           Provide a custom name to the pin.
        2) Select the USB Driver Component in MHC Project Graph and enable the  
           "Enable VBUS Sense" Check-box.     
        3) Specify the custom name of the VBUS SENSE pin in the "VBUS SENSE Pin Name" box.  */ 
static DRV_USB_VBUS_LEVEL DRV_USBFSV1_VBUS_Comparator(void)
{
    DRV_USB_VBUS_LEVEL retVal = DRV_USB_VBUS_LEVEL_INVALID;
    
    if(1U == USB_VBUS_SENSE_Get())
    {
        retVal = DRV_USB_VBUS_LEVEL_VALID;
    }
    return (retVal);

}

static const DRV_USBFSV1_INIT drvUSBInit =
{
    /* Interrupt Source for USB module */
    .interruptSource = USB_EORSMDNRSM_IRQn,
    .interruptSource1 = USB_SOFHSOF_IRQn,
    .interruptSource2 = USB_TRCPT00_IRQn,
    .interruptSource3 = USB_TRCPT10_IRQn,

    /* System module initialization */
    .moduleInit = {0},

    /* USB Controller to operate as USB Device */
    .operationMode = DRV_USBFSV1_OPMODE_DEVICE,

    /* USB Full Speed Operation */
    .operationSpeed = USB_SPEED_FULL,
    
    /* Stop in idle */
    .runInStandby = true,

    /* Suspend in sleep */
    .suspendInSleep = false,

    /* Identifies peripheral (PLIB-level) ID */
    .usbID = USB_REGS,

    /* Function to check for VBus */
    .vbusComparator = DRV_USBFSV1_VBUS_Comparator

};




// *****************************************************************************
// *****************************************************************************
// Section: System Initialization
// *****************************************************************************
// *****************************************************************************



// *****************************************************************************
// *****************************************************************************
// Section: Local initialization functions
// *****************************************************************************
// *****************************************************************************

/* MISRAC 2012 deviation block end */

/*******************************************************************************
  Function:
    void SYS_Initialize ( void *data )

  Summary:
    Initializes the board, services, drivers, application and other modules.

  Remarks:
 */

void SYS_Initialize ( void* data )
{

    /* MISRAC 2012 deviation block start */
    /* MISRA C-2012 Rule 2.2 deviated in this file.  Deviation record ID -  H3_MISRAC_2012_R_2_2_DR_1 */

  
    PORT_Initialize();

    CLOCK_Initialize();




    FCW_Initialize();

    EVSYS_Initialize();

    PM_Initialize();

    SERCOM4_USART_Initialize();

	BSP_Initialize();

    /* MISRAC 2012 deviation block start */
    /* Following MISRA-C rules deviated in this block  */
    /* MISRA C-2012 Rule 11.3 - Deviation record ID - H3_MISRAC_2012_R_11_3_DR_1 */
    /* MISRA C-2012 Rule 11.8 - Deviation record ID - H3_MISRAC_2012_R_11_8_DR_1 */

    sysObj.drvUsart0 = DRV_USART_Initialize(DRV_USART_INDEX_0, (SYS_MODULE_INIT *)&drvUsart0InitData);


    sysObj.drvMemory0 = DRV_MEMORY_Initialize((SYS_MODULE_INDEX)DRV_MEMORY_INDEX_0, (SYS_MODULE_INIT *)&drvMemory0InitData);




    /* Initialize the USB device layer */
    sysObj.usbDevObject0 = USB_DEVICE_Initialize (USB_DEVICE_INDEX_0 , ( SYS_MODULE_INIT* ) & usbDevInitData);


    /* Initialize USB Driver */ 
    sysObj.drvUSBFSV1Object = DRV_USBFSV1_Initialize(DRV_USBFSV1_INDEX_0, (SYS_MODULE_INIT *) &drvUSBInit);


    /* MISRAC 2012 deviation block end */
    APP_Initialize();


    NVIC_Initialize();


    /* MISRAC 2012 deviation block end */
}

/*******************************************************************************
 End of File
*/
