configName: sam_9x60_ek_iar
folderName: sam_9x60_ek_iar.IAR
format_version: v1.0
frameworkPath: C:\Repos\H3
processor: SAM9X60
projectName: cdc_msd_sdcard_sam_9x60_ek_iar
settings:
  PackageFilter: bsp;core;core_apps_sam_a7g5;csp;Devices;dev_packs;quick_docs;usb;usb_apps_device;usb_apps_dual_role;usb_apps_host;usb_apps_multi_controller
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAM9X60_DFP\1.6.61\atdf\SAM9X60.atdf
