configName: sam_a5d27_wlsom1_ek1_freertos
folderName: sam_a5d27_wlsom1_ek1_freertos
format_version: v1.0
frameworkPath: ..\..\..\..
processor: ATSAMA5D27CLD2G
projectName: msd_sdcard_sam_a5d27_wlsom1_ek1_freertos
settings:
  PackageFilter: bsp;core;core_apps_sam_9x60;core_apps_sam_a5d2;csp;csp_apps_pic32cm_le00_ls00;csp_apps_sam_9x60;csp_apps_sam_a5d2;usb;usb_apps_device;usb_apps_dual_role;usb_apps_host;usb_apps_multi_controller
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMA5D2_DFP\1.5.53\atdf\ATSAMA5D27CLD2G.atdf
