format_version: v1.0
type: UniqueComponent
attributes: {id: BSP_PIC32Z_CA90_Curiosity_Ultra, bsp: 'true'}
children:
- type: ElementPosition
  attributes: {x: '170', y: '60', id: BSP_PIC32Z_CA90_Curiosity_Ultra}
