format_version: v1.0
type: UniqueComponent
attributes: {id: peripheral_usb_0}
children:
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: USBHS0}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: drv_usbhs_index_0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: usb_peripheral_dependency}
- type: ElementPosition
  attributes: {x: '43', y: '182', id: peripheral_usb_0}
