configName: pic32cz_ca80_curiosity_ultra
folderName: pic32cz_ca80_curiosity_ultra
format_version: v1.0
frameworkPath: C:\v3_Bitbucket
processor: PIC32CZ8110CA90208
projectName: pic32cz_ca80_curiosity_ultra
settings:
  PackageFilter: bsp;core;core_apps_pic32cz_ca;core_apps_sam_9x60;core_apps_sam_9x7;core_apps_sam_a5d2;core_apps_sam_a7g5;csp;csp_apps_pic32cm_le_ls;csp_apps_pic32cz_ca;Devices;dev_packs;harmony-services;quick_docs;usb;usb_apps_device;usb_apps_dual_role;usb_apps_host;usb_apps_multi_controller
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32CZ-CA90_DFP\1.0.14\CA90\atdf\PIC32CZ8110CA90208.atdf
