format_version: v1.0
type: GeneratorComponent
attributes: {id: usb_device}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: CONFIG_USB_DEVICE_SPEED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_usbhs_index_0, value: High Speed}
- type: Instances
  children:
  - type: InstanceComponent
    attributes: {instance: '0', id: usb_device}
    children:
    - type: Symbols
      children:
      - type: Integer
        attributes: {id: CONFIG_USB_DEVICE_CONFIG_DESCRPTR_SIZE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_0, value: '41'}
      - type: Integer
        attributes: {id: CONFIG_USB_DEVICE_ENDPOINTS_NUMBER}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_0, value: '1'}
      - type: Integer
        attributes: {id: CONFIG_USB_DEVICE_FUNCTIONS_NUMBER}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_0, value: '1'}
      - type: Integer
        attributes: {id: CONFIG_USB_DEVICE_INTERFACES_NUMBER}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_0, value: '1'}
      - type: Boolean
        attributes: {id: CONFIG_USB_DEVICE_MSD_DISK_IMAGE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_0, value: 'false'}
      - type: String
        attributes: {id: CONFIG_USB_DEVICE_PRODUCT_ID_IDX0}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_0, value: '0x003F'}
      - type: Combo
        attributes: {id: CONFIG_USB_DEVICE_PRODUCT_ID_SELECTION_IDX0}
        children:
        - type: Values
          children:
          - type: User
            attributes: {value: hid_basic_demo}
      - type: String
        attributes: {id: CONFIG_USB_DEVICE_PRODUCT_STRING_DESCRIPTOR}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_0, value: Simple HID Device Demo}
      - type: String
        attributes: {id: CONFIG_USB_DEVICE_SPEED}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_0, value: High Speed}
      - type: String
        attributes: {id: USB_DEVICE_INDEX}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_0, value: DRV_USBHS_INDEX_0}
      - type: File
        attributes: {id: USB_DEVICE_SYS_RTOS_TASK}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: enabled}
            children:
            - {type: Value, value: 'false'}
    - type: Attachments
      children:
      - type: DirectCapability
        attributes: {id: USB Device}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: usb_device_hid_0}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: usb_device_dependency}
      - type: DirectDependency
        attributes: {id: usb_driver_dependency}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: drv_usbhs_index_0}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: DRV_USB}
- type: ElementPosition
  attributes: {x: '353', y: '168', id: usb_device}
