configName: sam_a7g5_ek
folderName: sam_a7g5_ek
format_version: v1.0
frameworkPath: ..\..\..
processor: SAMA7G54
projectName: cdc_com_port_dual_sam_a7g5_ek
settings:
  PackageFilter: bootloader;bsp;core;core_apps_pic32mx;core_apps_sam_9x60;core_apps_sam_a5d2;core_apps_sam_a7g5;csp;csp_apps_pic32cm_le00_ls00;csp_apps_sam_9x60;csp_apps_sam_a5d2;csp_apps_sam_a7g5;quick_docs;usb;usb_apps_device;usb_apps_dual_role;usb_apps_host;usb_apps_multi_controller
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: SAMA7G5_DFP\1.2.178
