configName: pic32mk_gp_db
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: PIC32MK1024GPE100
projectName: ''
settings:
  PackageFilter: audio;bsp;core;csp;quick_docs;usb;usb_apps_device;usb_apps_dual_role;usb_apps_host;usb_apps_multi_controller
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: PIC32MK-GP_DFP\1.6.144
