configName: sam_d11_xpro_iar
folderName: sam_d11_xpro_iar.IAR
format_version: v1.0
frameworkPath: C:\jcb\usb\repo\H3
processor: ATSAMD11D14AM
projectName: cdc_com_port_single_sam_d11_xpro_iar
settings:
  PackageFilter: bootloader;bsp;core;core_apps_pic32mx;core_apps_sam_9x60;core_apps_sam_a5d2;core_apps_sam_a7g5;csp;csp_apps_pic32cm_le00_ls00;csp_apps_sam_9x60;csp_apps_sam_a5d2;csp_apps_sam_a7g5;quick_docs;usb;usb_apps_device;usb_apps_dual_role;usb_apps_host;usb_apps_multi_controller
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMD11_DFP\2.4.56\atdf\ATSAMD11D14AM.atdf
