/*******************************************************************************
  System Initialization File

  File Name:
    initialization.c

  Summary:
    This file contains source code necessary to initialize the system.

  Description:
    This file contains source code necessary to initialize the system.  It
    implements the "SYS_Initialize" function, defines the configuration bits,
    and allocates any necessary global system resources,
 *******************************************************************************/

// DOM-IGNORE-BEGIN
/*******************************************************************************
* Copyright (C) 2018 Microchip Technology Inc. and its subsidiaries.
*
* Subject to your compliance with these terms, you may use Microchip software
* and any derivatives exclusively with Microchip products. It is your
* responsibility to comply with third party license terms applicable to your
* use of third party software (including open source software) that may
* accompany Microchip software.
*
* THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
* EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
* WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
* PARTICULAR PURPOSE.
*
* IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
* INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
* WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
* BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
* FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
* ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
* THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *******************************************************************************/
// DOM-IGNORE-END

// *****************************************************************************
// *****************************************************************************
// Section: Included Files
// *****************************************************************************
// *****************************************************************************
#include "configuration.h"
#include "definitions.h"
#include "device.h"


// ****************************************************************************
// ****************************************************************************
// Section: Configuration Bits
// ****************************************************************************
// ****************************************************************************
#pragma config FUSES_BOOTCFG1_DEVSIGN_SEQ = 0x1U
#pragma config FUSES_BOOTCFG1_DEVSIGN_SEQBAR = 0xfffeU
#pragma config FUSES_BOOTCFG1_BOOT_FLAG_PUFRETRY = CLEAR
#pragma config FUSES_BOOTCFG1_BOOT_FLAG_PUFSTARTUP = CLEAR
#pragma config FUSES_BOOTCFG1_BOOT_FLAG_DICEDIS = SET
#pragma config FUSES_BOOTCFG1_BOOT_FLAG_BOOTMODE = SET
#pragma config FUSES_BOOTCFG1_BOOT_FLAG_RAM_INIT_ENB = SET
#pragma config FUSES_BOOTCFG1_BOOT_FLAG_PUFSCORE = 0x0U
#pragma config FUSES_BOOTCFG1_DICE_CDI_INDEX_DICE_CDI_INDEX = 0x7fU
#pragma config FUSES_BOOTCFG1_DICE_FW_HASH_INDEX_DICE_FW_HASH_INDEX = 0x7fU
#pragma config FUSES_BOOTCFG1_BOOT_GPIOSEL_GPIOPINSEL = 0x1fU
#pragma config FUSES_BOOTCFG1_BOOT_GPIOSEL_GPIOPORTSEL = 0xfU
#pragma config FUSES_BOOTCFG1_BOOT_GPIOSEL_FLTPOL = SET
#pragma config FUSES_BOOTCFG1_BOOT_GPIOSEL_FLTODRAIN = SET
#pragma config FUSES_BOOTCFG1_BOOT_GPIOSEL_FLTSLEWLIM = 0x3U
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC0 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC1 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC2 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC3 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC4 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC5 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC6 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC7 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC8 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC9 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC10 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC11 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC12 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC13 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC14 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC15 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC16 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC17 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC18 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC19 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC20 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC21 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC22 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC23 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC24 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC25 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC26 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC27 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC28 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC29 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC30 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECCLRA_NONSEC31 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC0 = SET
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC1 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC2 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC3 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC4 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC5 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC6 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC7 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC8 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC9 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC10 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC11 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC12 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC13 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC14 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC15 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC16 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC17 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC18 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC19 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC20 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC21 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC22 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC23 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC24 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC25 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC26 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC27 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC28 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC29 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC30 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB0_NONSECSETA_NONSEC31 = CLEAR
#pragma config FUSES_BOOTCFG1_PAC_WRCTRL_H2PB0_PERID = 0x13U
#pragma config FUSES_BOOTCFG1_PAC_WRCTRL_H2PB0_KEY = OFF
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC0 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC1 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC2 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC3 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC4 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC5 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC6 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC7 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC8 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC9 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC10 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC11 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC12 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC13 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC14 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC15 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC16 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC17 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC18 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC19 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC20 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC21 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC22 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC23 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC24 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC25 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC26 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC27 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC28 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC29 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC30 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECCLRA_NONSEC31 = SET
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC0 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC1 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC2 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC3 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC4 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC5 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC6 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC7 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC8 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC9 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC10 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC11 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC12 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC13 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC14 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC15 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC16 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC17 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC18 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC19 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC20 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC21 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC22 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC23 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC24 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC25 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC26 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC27 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC28 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC29 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC30 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB1_NONSECSETA_NONSEC31 = CLEAR
#pragma config FUSES_BOOTCFG1_PAC_WRCTRL_H2PB1_PERID = 0x2eU
#pragma config FUSES_BOOTCFG1_PAC_WRCTRL_H2PB1_KEY = OFF
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC0 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC1 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC2 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC3 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC4 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC5 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC6 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC7 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC8 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC9 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC10 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC11 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC12 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC13 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC14 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC15 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC16 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC17 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC18 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC19 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC20 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC21 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC22 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC23 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC24 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC25 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC26 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC27 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC28 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC29 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC30 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECCLRA_NONSEC31 = SET
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC0 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC1 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC2 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC3 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC4 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC5 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC6 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC7 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC8 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC9 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC10 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC11 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC12 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC13 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC14 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC15 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC16 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC17 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC18 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC19 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC20 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC21 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC22 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC23 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC24 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC25 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC26 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC27 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC28 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC29 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC30 = CLEAR
#pragma config FUSES_BOOTCFG1_H2PB2_NONSECSETA_NONSEC31 = CLEAR
#pragma config FUSES_BOOTCFG1_PAC_WRCTRL_H2PB2_PERID = 0x2fU
#pragma config FUSES_BOOTCFG1_PAC_WRCTRL_H2PB2_KEY = OFF
#pragma config FUSES_BOOTCFG1_IDAU_RCTRL_BFM_ARG = 0x0U
#pragma config FUSES_BOOTCFG1_IDAU_RCTRL_BFM_CMD = WRSZ
#pragma config FUSES_BOOTCFG1_IDAU_RCTRL_PFMANS_ARG = 0x0U
#pragma config FUSES_BOOTCFG1_IDAU_RCTRL_PFMANS_CMD = WRSZ
#pragma config FUSES_BOOTCFG1_IDAU_RCTRL_PFMANSC_ARG = 0x0U
#pragma config FUSES_BOOTCFG1_IDAU_RCTRL_PFMANSC_CMD = WRSZ
#pragma config FUSES_BOOTCFG1_IDAU_RCTRL_DRM_ARG = 0x0U
#pragma config FUSES_BOOTCFG1_IDAU_RCTRL_DRM_CMD = WRSZ
#pragma config FUSES_BOOTCFG1_IDAU_CTRL_EN_CMD = ENABLE
#pragma config FUSES_BOOTCFG1_IDAU_CTRL_WLCK_CMD = WLCK
#pragma config FUSES_BOOTCFG1_FCW_CWP_BC1AWP = DISABLE
#pragma config FUSES_BOOTCFG1_FCW_CWP_BC1WP = DISABLE
#pragma config FUSES_BOOTCFG1_FCW_CWP_RCWP = DISABLE
#pragma config FUSES_BOOTCFG1_FCW_CWP_VSSWP0 = DISABLE
#pragma config FUSES_BOOTCFG1_FCW_CWP_VSSWP1 = DISABLE
#pragma config FUSES_BOOTCFG1_FCW_CWP_BC1AWPLOCK = UNLOCKED
#pragma config FUSES_BOOTCFG1_FCW_CWP_BC1WPLOCK = UNLOCKED
#pragma config FUSES_BOOTCFG1_FCW_CWP_RCWPLOCK = UNLOCKED
#pragma config FUSES_BOOTCFG1_FCW_CWP_VSSWPLOCK0 = UNLOCKED
#pragma config FUSES_BOOTCFG1_FCW_CWP_VSSWPLOCK1 = UNLOCKED
#pragma config FUSES_BOOTCFG1_FCR_CRP_BC1ARP = DISABLE
#pragma config FUSES_BOOTCFG1_FCR_CRP_BC1RP = DISABLE
#pragma config FUSES_BOOTCFG1_FCR_CRP_RCRP = DISABLE
#pragma config FUSES_BOOTCFG1_FCR_CRP_VSSRP0 = DISABLE
#pragma config FUSES_BOOTCFG1_FCR_CRP_VSSRP1 = DISABLE
#pragma config FUSES_BOOTCFG1_FCR_CRP_BC1ARPLOCK = UNLOCKED
#pragma config FUSES_BOOTCFG1_FCR_CRP_BC1RPLOCK = UNLOCKED
#pragma config FUSES_BOOTCFG1_FCR_CRP_RCRPLOCK = UNLOCKED
#pragma config FUSES_BOOTCFG1_FCR_CRP_VSSRPLOCK0 = UNLOCKED
#pragma config FUSES_BOOTCFG1_FCR_CRP_VSSRPLOCK1 = UNLOCKED
#pragma config FUSES_BOOTCFG1_FCR_ECCCTRL_ECCCTL = STRICT
#pragma config FUSES_BOOTCFG1_FCR_ECCCTRL_ECCUNLCK = LOCKED
#pragma config FUSES_BOOTCFG1_FCR_ECCCTRL_SECCNT = 0x0U
#pragma config FUSES_BOOTCFG1_SUPC_BRCFGUSMOR_BOR_HYST_BOR_VDDIO = LOW
#pragma config FUSES_BOOTCFG1_SUPC_BRCFGUSMOR_BOR_BOR_TRIP_VDDIO = 0x0U
#pragma config FUSES_BOOTCFG1_SUPC_BRCFGUSMOR_BOR_HYST_BOR_VDDREG = LOW
#pragma config FUSES_BOOTCFG1_SUPC_BRCFGUDSSMOR_BOR_HYST = LOW
#pragma config FUSES_BOOTCFG1_SUPC_BRCFGUDSSMOR_BOR_TRIP = 0x0U
#pragma config FUSES_BOOTCFG1_SUPC_BRCFGUCP0_CP = 0x0U
#pragma config FUSES_BOOTCFG1_WDT_SETUP_ENABLE = CLEAR
#pragma config FUSES_BOOTCFG1_WDT_SETUP_WEN = CLEAR
#pragma config FUSES_BOOTCFG1_WDT_SETUP_RUNSTDBY = CLEAR
#pragma config FUSES_BOOTCFG1_WDT_SETUP_ALWAYSON = CLEAR
#pragma config FUSES_BOOTCFG1_WDT_SETUP_PER = CYC8
#pragma config FUSES_BOOTCFG1_WDT_SETUP_WINDOW = CYC8
#pragma config FUSES_BOOTCFG1_WDT_SETUP_EWOFFSET = CYC8
#pragma config FUSES_BOOTCFG1A_DEVSIGN_SEQ = 0x2U
#pragma config FUSES_BOOTCFG1A_DEVSIGN_SEQBAR = 0xfffdU
#pragma config FUSES_BOOTCFG1A_BOOT_FLAG_PUFRETRY = CLEAR
#pragma config FUSES_BOOTCFG1A_BOOT_FLAG_PUFSTARTUP = CLEAR
#pragma config FUSES_BOOTCFG1A_BOOT_FLAG_DICEDIS = SET
#pragma config FUSES_BOOTCFG1A_BOOT_FLAG_BOOTMODE = SET
#pragma config FUSES_BOOTCFG1A_BOOT_FLAG_RAM_INIT_ENB = SET
#pragma config FUSES_BOOTCFG1A_BOOT_FLAG_PUFSCORE = 0x0U
#pragma config FUSES_BOOTCFG1A_DICE_CDI_INDEX_DICE_CDI_INDEX = 0x7fU
#pragma config FUSES_BOOTCFG1A_DICE_FW_HASH_INDEX_DICE_FW_HASH_INDEX = 0x7fU
#pragma config FUSES_BOOTCFG1A_BOOT_GPIOSEL_GPIOPINSEL = 0x1fU
#pragma config FUSES_BOOTCFG1A_BOOT_GPIOSEL_GPIOPORTSEL = 0xfU
#pragma config FUSES_BOOTCFG1A_BOOT_GPIOSEL_FLTPOL = SET
#pragma config FUSES_BOOTCFG1A_BOOT_GPIOSEL_FLTODRAIN = SET
#pragma config FUSES_BOOTCFG1A_BOOT_GPIOSEL_FLTSLEWLIM = 0x3U
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC0 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC1 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC2 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC3 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC4 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC5 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC6 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC7 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC8 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC9 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC10 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC11 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC12 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC13 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC14 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC15 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC16 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC17 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC18 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC19 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC20 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC21 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC22 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC23 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC24 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC25 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC26 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC27 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC28 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC29 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC30 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECCLRA_NONSEC31 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC0 = SET
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC1 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC2 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC3 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC4 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC5 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC6 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC7 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC8 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC9 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC10 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC11 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC12 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC13 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC14 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC15 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC16 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC17 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC18 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC19 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC20 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC21 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC22 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC23 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC24 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC25 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC26 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC27 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC28 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC29 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC30 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB0_NONSECSETA_NONSEC31 = CLEAR
#pragma config FUSES_BOOTCFG1A_PAC_WRCTRL_H2PB0_PERID = 0x13U
#pragma config FUSES_BOOTCFG1A_PAC_WRCTRL_H2PB0_KEY = OFF
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC0 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC1 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC2 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC3 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC4 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC5 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC6 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC7 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC8 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC9 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC10 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC11 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC12 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC13 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC14 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC15 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC16 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC17 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC18 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC19 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC20 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC21 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC22 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC23 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC24 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC25 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC26 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC27 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC28 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC29 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC30 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECCLRA_NONSEC31 = SET
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC0 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC1 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC2 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC3 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC4 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC5 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC6 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC7 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC8 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC9 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC10 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC11 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC12 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC13 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC14 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC15 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC16 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC17 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC18 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC19 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC20 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC21 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC22 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC23 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC24 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC25 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC26 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC27 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC28 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC29 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC30 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB1_NONSECSETA_NONSEC31 = CLEAR
#pragma config FUSES_BOOTCFG1A_PAC_WRCTRL_H2PB1_PERID = 0x2eU
#pragma config FUSES_BOOTCFG1A_PAC_WRCTRL_H2PB1_KEY = OFF
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC0 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC1 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC2 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC3 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC4 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC5 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC6 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC7 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC8 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC9 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC10 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC11 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC12 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC13 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC14 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC15 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC16 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC17 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC18 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC19 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC20 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC21 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC22 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC23 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC24 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC25 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC26 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC27 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC28 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC29 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC30 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECCLRA_NONSEC31 = SET
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC0 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC1 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC2 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC3 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC4 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC5 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC6 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC7 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC8 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC9 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC10 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC11 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC12 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC13 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC14 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC15 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC16 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC17 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC18 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC19 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC20 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC21 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC22 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC23 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC24 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC25 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC26 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC27 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC28 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC29 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC30 = CLEAR
#pragma config FUSES_BOOTCFG1A_H2PB2_NONSECSETA_NONSEC31 = CLEAR
#pragma config FUSES_BOOTCFG1A_PAC_WRCTRL_H2PB2_PERID = 0x2fU
#pragma config FUSES_BOOTCFG1A_PAC_WRCTRL_H2PB2_KEY = OFF
#pragma config FUSES_BOOTCFG1A_IDAU_RCTRL_BFM_ARG = 0x0U
#pragma config FUSES_BOOTCFG1A_IDAU_RCTRL_BFM_CMD = WRSZ
#pragma config FUSES_BOOTCFG1A_IDAU_RCTRL_PFMANS_ARG = 0x0U
#pragma config FUSES_BOOTCFG1A_IDAU_RCTRL_PFMANS_CMD = WRSZ
#pragma config FUSES_BOOTCFG1A_IDAU_RCTRL_PFMANSC_ARG = 0x0U
#pragma config FUSES_BOOTCFG1A_IDAU_RCTRL_PFMANSC_CMD = WRSZ
#pragma config FUSES_BOOTCFG1A_IDAU_RCTRL_DRM_ARG = 0x0U
#pragma config FUSES_BOOTCFG1A_IDAU_RCTRL_DRM_CMD = WRSZ
#pragma config FUSES_BOOTCFG1A_IDAU_CTRL_EN_CMD = ENABLE
#pragma config FUSES_BOOTCFG1A_IDAU_CTRL_WLCK_CMD = WLCK
#pragma config FUSES_BOOTCFG1A_FCW_CWP_BC1AWP = DISABLE
#pragma config FUSES_BOOTCFG1A_FCW_CWP_BC1WP = DISABLE
#pragma config FUSES_BOOTCFG1A_FCW_CWP_RCWP = DISABLE
#pragma config FUSES_BOOTCFG1A_FCW_CWP_VSSWP0 = DISABLE
#pragma config FUSES_BOOTCFG1A_FCW_CWP_VSSWP1 = DISABLE
#pragma config FUSES_BOOTCFG1A_FCW_CWP_BC1AWPLOCK = UNLOCKED
#pragma config FUSES_BOOTCFG1A_FCW_CWP_BC1WPLOCK = UNLOCKED
#pragma config FUSES_BOOTCFG1A_FCW_CWP_RCWPLOCK = UNLOCKED
#pragma config FUSES_BOOTCFG1A_FCW_CWP_VSSWPLOCK0 = UNLOCKED
#pragma config FUSES_BOOTCFG1A_FCW_CWP_VSSWPLOCK1 = UNLOCKED
#pragma config FUSES_BOOTCFG1A_FCR_CRP_BC1ARP = DISABLE
#pragma config FUSES_BOOTCFG1A_FCR_CRP_BC1RP = DISABLE
#pragma config FUSES_BOOTCFG1A_FCR_CRP_RCRP = DISABLE
#pragma config FUSES_BOOTCFG1A_FCR_CRP_VSSRP0 = DISABLE
#pragma config FUSES_BOOTCFG1A_FCR_CRP_VSSRP1 = DISABLE
#pragma config FUSES_BOOTCFG1A_FCR_CRP_BC1ARPLOCK = UNLOCKED
#pragma config FUSES_BOOTCFG1A_FCR_CRP_BC1RPLOCK = UNLOCKED
#pragma config FUSES_BOOTCFG1A_FCR_CRP_RCRPLOCK = UNLOCKED
#pragma config FUSES_BOOTCFG1A_FCR_CRP_VSSRPLOCK0 = UNLOCKED
#pragma config FUSES_BOOTCFG1A_FCR_CRP_VSSRPLOCK1 = UNLOCKED
#pragma config FUSES_BOOTCFG1A_FCR_ECCCTRL_ECCCTL = STRICT
#pragma config FUSES_BOOTCFG1A_FCR_ECCCTRL_ECCUNLCK = LOCKED
#pragma config FUSES_BOOTCFG1A_FCR_ECCCTRL_SECCNT = 0x0U
#pragma config FUSES_BOOTCFG1A_SUPC_BRCFGUSMOR_BOR_HYST_BOR_VDDIO = LOW
#pragma config FUSES_BOOTCFG1A_SUPC_BRCFGUSMOR_BOR_BOR_TRIP_VDDIO = 0x0U
#pragma config FUSES_BOOTCFG1A_SUPC_BRCFGUSMOR_BOR_HYST_BOR_VDDREG = LOW
#pragma config FUSES_BOOTCFG1A_SUPC_BRCFGUDSSMOR_BOR_HYST = LOW
#pragma config FUSES_BOOTCFG1A_SUPC_BRCFGUDSSMOR_BOR_TRIP = 0x0U
#pragma config FUSES_BOOTCFG1A_SUPC_BRCFGUCP0_CP = 0x0U
#pragma config FUSES_BOOTCFG1A_WDT_SETUP_ENABLE = CLEAR
#pragma config FUSES_BOOTCFG1A_WDT_SETUP_WEN = CLEAR
#pragma config FUSES_BOOTCFG1A_WDT_SETUP_RUNSTDBY = CLEAR
#pragma config FUSES_BOOTCFG1A_WDT_SETUP_ALWAYSON = CLEAR
#pragma config FUSES_BOOTCFG1A_WDT_SETUP_PER = CYC8
#pragma config FUSES_BOOTCFG1A_WDT_SETUP_WINDOW = CYC8
#pragma config FUSES_BOOTCFG1A_WDT_SETUP_EWOFFSET = CYC8




// *****************************************************************************
// *****************************************************************************
// Section: Driver Initialization Data
// *****************************************************************************
// *****************************************************************************
/* Following MISRA-C rules are deviated in the below code block */
/* MISRA C-2012 Rule 7.2 - Deviation record ID - H3_MISRAC_2012_R_7_2_DR_1 */
/* MISRA C-2012 Rule 11.1 - Deviation record ID - H3_MISRAC_2012_R_11_1_DR_1 */
/* MISRA C-2012 Rule 11.3 - Deviation record ID - H3_MISRAC_2012_R_11_3_DR_1 */
/* MISRA C-2012 Rule 11.8 - Deviation record ID - H3_MISRAC_2012_R_11_8_DR_1 */
// <editor-fold defaultstate="collapsed" desc="DRV_SDSPI Instance 0 Initialization Data">

/* SDSPI Client Objects Pool */
static DRV_SDSPI_CLIENT_OBJ drvSDSPI0ClientObjPool[DRV_SDSPI_CLIENTS_NUMBER_IDX0];

/* SDSPI Transfer Objects Pool */
static DRV_SDSPI_BUFFER_OBJ drvSDSPI0TransferObjPool[DRV_SDSPI_QUEUE_SIZE_IDX0];

/* SPI PLIB Interface Initialization for SDSPI Driver */
static const DRV_SDSPI_PLIB_INTERFACE drvSDSPI0PlibAPI = {

    /* SPI PLIB WriteRead function */
    .writeRead = (DRV_SDSPI_PLIB_WRITEREAD)SERCOM2_SPI_WriteRead,

    /* SPI PLIB Write function */
    .write_t = (DRV_SDSPI_PLIB_WRITE)SERCOM2_SPI_Write,

    /* SPI PLIB Read function */
    .read_t = (DRV_SDSPI_PLIB_READ)SERCOM2_SPI_Read,

    /* SPI PLIB Transfer Status function */
    .isTransmitterBusy = (DRV_SPI_PLIB_TRANSMITTER_IS_BUSY)SERCOM2_SPI_IsTransmitterBusy,

    .transferSetup = (DRV_SDSPI_PLIB_SETUP)SERCOM2_SPI_TransferSetup,

    /* SPI PLIB Callback Register */
    .callbackRegister = (DRV_SDSPI_PLIB_CALLBACK_REGISTER)SERCOM2_SPI_CallbackRegister,
};

static const uint32_t drvSDSPI0remapDataBits[]= { 0x0, 0x1, 0xFFFFFFFFU, 0xFFFFFFFFU, 0xFFFFFFFFU, 0xFFFFFFFFU, 0xFFFFFFFFU, 0xFFFFFFFFU, 0xFFFFFFFFU };
static const uint32_t drvSDSPI0remapClockPolarity[] = { 0x0, 0x20000000 };
static const uint32_t drvSDSPI0remapClockPhase[] = { 0x10000000, 0x0 };

/* SDSPI Driver Initialization Data */
static const DRV_SDSPI_INIT drvSDSPI0InitData =
{
    /* SD Card SPI PLIB API interface*/
    .spiPlib                = &drvSDSPI0PlibAPI,

    .remapDataBits          = drvSDSPI0remapDataBits,

    .remapClockPolarity     = drvSDSPI0remapClockPolarity,

    .remapClockPhase        = drvSDSPI0remapClockPhase,


    /* SDSPI Number of clients */
    .numClients             = DRV_SDSPI_CLIENTS_NUMBER_IDX0,

    /* SDSPI Client Objects Pool */
    .clientObjPool          = (uintptr_t)&drvSDSPI0ClientObjPool[0],

    /* SDSPI Transfer Objects Pool */
    .bufferObjPool          = (uintptr_t)&drvSDSPI0TransferObjPool[0],

    /* SDSPI Transfer Objects Queue Size */
    .bufferObjPoolSize      = DRV_SDSPI_QUEUE_SIZE_IDX0,

    .chipSelectPin          = DRV_SDSPI_CHIP_SELECT_PIN_IDX0,

    .sdcardSpeedHz          = DRV_SDSPI_SPEED_HZ_IDX0,

    .pollingIntervalMs      = DRV_SDSPI_POLLING_INTERVAL_MS_IDX0,

    .writeProtectPin        = SYS_PORT_PIN_NONE,

    .isFsEnabled            = false,

};
// </editor-fold>




// *****************************************************************************
// *****************************************************************************
// Section: System Data
// *****************************************************************************
// *****************************************************************************
/* Structure to hold the object handles for the modules in the system. */
SYSTEM_OBJECTS sysObj;

// *****************************************************************************
// *****************************************************************************
// Section: Library/Stack Initialization Data
// *****************************************************************************
// *****************************************************************************
/******************************************************
 * USB Driver Initialization
 ******************************************************/
 
/*  When designing a Self-powered USB Device, the application should make sure
    that USB_DEVICE_Attach() function is called only when VBUS is actively powered.
    Therefore, the firmware needs some means to detect when the Host is powering 
    the VBUS. A 5V tolerant I/O pin can be connected to VBUS (through a resistor)
    and can be used to detect when VBUS is high or low. The application can specify
    a VBUS Detect function through the USB Driver Initialize data structure. 
    The USB device stack will periodically call this function. If the VBUS is 
    detected, the USB_DEVICE_EVENT_POWER_DETECTED event is generated. If the VBUS 
    is removed (i.e., the device is physically detached from Host), the USB stack 
    will generate the event USB_DEVICE_EVENT_POWER_REMOVED. The application should 
    call USB_DEVICE_Detach() when VBUS is removed. 
    
    The following are the steps to generate the VBUS_SENSE Function through MHC     
        1) Navigate to MHC->Tools->Pin Configuration and Configure the pin used 
           as VBUS_SENSE. Set this pin Function as "GPIO" and set as "Input". 
           Provide a custom name to the pin.
        2) Select the USB Driver Component in MHC Project Graph and enable the  
           "Enable VBUS Sense" Check-box.     
        3) Specify the custom name of the VBUS SENSE pin in the "VBUS SENSE Pin Name" box.  */ 
static DRV_USB_VBUS_LEVEL DRV_USBFSV1_VBUS_Comparator(void)
{
    DRV_USB_VBUS_LEVEL retVal = DRV_USB_VBUS_LEVEL_INVALID;
    
    if(1U == USB_VBUS_SENSE_Get())
    {
        retVal = DRV_USB_VBUS_LEVEL_VALID;
    }
    return (retVal);

}

static const DRV_USBFSV1_INIT drvUSBInit =
{
    /* Interrupt Source for USB module */
    .interruptSource = USB_EORSMDNRSM_IRQn,
    .interruptSource1 = USB_SOFHSOF_IRQn,
    .interruptSource2 = USB_TRCPT00_IRQn,
    .interruptSource3 = USB_TRCPT10_IRQn,

    /* System module initialization */
    .moduleInit = {0},

    /* USB Controller to operate as USB Device */
    .operationMode = DRV_USBFSV1_OPMODE_DEVICE,

    /* USB Full Speed Operation */
    .operationSpeed = USB_SPEED_FULL,
    
    /* Stop in idle */
    .runInStandby = true,

    /* Suspend in sleep */
    .suspendInSleep = false,

    /* Identifies peripheral (PLIB-level) ID */
    .usbID = USB_REGS,

    /* Function to check for VBus */
    .vbusComparator = DRV_USBFSV1_VBUS_Comparator

};




// *****************************************************************************
// *****************************************************************************
// Section: System Initialization
// *****************************************************************************
// *****************************************************************************
// <editor-fold defaultstate="collapsed" desc="SYS_TIME Initialization Data">

static const SYS_TIME_PLIB_INTERFACE sysTimePlibAPI = {
    .timerCallbackSet = (SYS_TIME_PLIB_CALLBACK_REGISTER)SYSTICK_TimerCallbackSet,
    .timerStart = (SYS_TIME_PLIB_START)SYSTICK_TimerStart,
    .timerStop = (SYS_TIME_PLIB_STOP)SYSTICK_TimerStop,
    .timerFrequencyGet = (SYS_TIME_PLIB_FREQUENCY_GET)SYSTICK_TimerFrequencyGet,
    .timerInterruptRestore = (SYS_TIME_PLIB_INTERRUPT_RESTORE)SYSTICK_TimerInterruptRestore,
    .timerInterruptDisable = (SYS_TIME_PLIB_INTERRUPT_DISABLE)SYSTICK_TimerInterruptDisable,
    .timerPeriodSet = (SYS_TIME_PLIB_PERIOD_SET)SYSTICK_TimerPeriodSet,
};

static const SYS_TIME_INIT sysTimeInitData =
{
    .timePlib = &sysTimePlibAPI,
    .hwTimerIntNum = SysTick_IRQn,
};

// </editor-fold>



// *****************************************************************************
// *****************************************************************************
// Section: Local initialization functions
// *****************************************************************************
// *****************************************************************************

/* MISRAC 2012 deviation block end */

/*******************************************************************************
  Function:
    void SYS_Initialize ( void *data )

  Summary:
    Initializes the board, services, drivers, application and other modules.

  Remarks:
 */

void SYS_Initialize ( void* data )
{

    /* MISRAC 2012 deviation block start */
    /* MISRA C-2012 Rule 2.2 deviated in this file.  Deviation record ID -  H3_MISRAC_2012_R_2_2_DR_1 */

  
    PORT_Initialize();

    CLOCK_Initialize();




    SERCOM2_SPI_Initialize();

    EVSYS_Initialize();

	SYSTICK_TimerInitialize();
    DMAC_Initialize();

    PM_Initialize();

	BSP_Initialize();

    /* MISRAC 2012 deviation block start */
    /* Following MISRA-C rules deviated in this block  */
    /* MISRA C-2012 Rule 11.3 - Deviation record ID - H3_MISRAC_2012_R_11_3_DR_1 */
    /* MISRA C-2012 Rule 11.8 - Deviation record ID - H3_MISRAC_2012_R_11_8_DR_1 */

    /* Initialize SDSPI0 Driver Instance */
    sysObj.drvSDSPI0 = DRV_SDSPI_Initialize(DRV_SDSPI_INDEX_0, (SYS_MODULE_INIT *)&drvSDSPI0InitData);


    /* MISRA C-2012 Rule 11.3, 11.8 deviated below. Deviation record ID -  
    H3_MISRAC_2012_R_11_3_DR_1 & H3_MISRAC_2012_R_11_8_DR_1*/
        
    sysObj.sysTime = SYS_TIME_Initialize(SYS_TIME_INDEX_0, (SYS_MODULE_INIT *)&sysTimeInitData);
    
    /* MISRAC 2012 deviation block end */


    /* Initialize the USB device layer */
    sysObj.usbDevObject0 = USB_DEVICE_Initialize (USB_DEVICE_INDEX_0 , ( SYS_MODULE_INIT* ) & usbDevInitData);


    /* Initialize USB Driver */ 
    sysObj.drvUSBFSV1Object = DRV_USBFSV1_Initialize(DRV_USBFSV1_INDEX_0, (SYS_MODULE_INIT *) &drvUSBInit);


    /* MISRAC 2012 deviation block end */
    APP_Initialize();


    NVIC_Initialize();


    /* MISRAC 2012 deviation block end */
}

/*******************************************************************************
 End of File
*/
