configName: pic32cm_le00_curiosity_pro
folderName: pic32cm_le00_curiosity_pro
format_version: v1.0
frameworkPath: ..\..\..
processor: PIC32CM5164LE00100
projectName: msd_basic_pic32cm_le00_curiosity_pro
settings:
  PackageFilter: bsp;core;core_apps_pic32mx;core_apps_sam_9x60;core_apps_sam_a5d2;core_apps_sam_a7g5;core_apps_sam_e70_s70_v70_v71;csp;csp_apps_pic32cm_le00_ls00;csp_apps_sam_9x60;csp_apps_sam_a5d2;csp_apps_sam_a7g5;csp_apps_sam_e70_s70_v70_v71;quick_docs;usb;usb_apps_device;usb_apps_dual_role;usb_apps_host;usb_apps_multi_controller
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32CM-LE_DFP\1.0.134\atdf\PIC32CM5164LE00100.atdf
